<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TNR POS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9de94897-b3b0-4a98-907f-28e83f0f3df7</testSuiteGuid>
   <testCaseLink>
      <guid>c568e79b-ca5f-49c9-908c-d5969ebf988e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/01 - Ajouter article ou ordre de Transfert</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d6ad66b-c2e0-49eb-8908-6a695c93ad9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>222dd0ca-23ea-47d6-b7f9-36545dfe252e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>401216dd-cef6-46f0-a1e6-04e0151498a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ece6b6f7-d58c-4f72-aab6-2b4476545c7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25453189-8697-4f9a-b71d-6582a2325be0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/02 - Ajouter d autre article</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8c9c2b3-dee6-4f63-b2d6-968e1820ef7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8537b5ee-7557-48f1-9911-31f2859c6578</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dddee581-ddfb-4017-9bbc-fc37e187589b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5296de99-cbb1-4cd3-a8ec-878d51faf0ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23c7ce3f-20d5-423c-8786-ab44d530b540</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/03 - Vérification statut article</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>731e37c1-5dfc-48c2-bac0-2b351e7f5fe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfbd2f64-374c-4b78-a344-3a6c2025dd92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57334ba6-5d3f-4585-b915-010bb5ba5ac6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b23a970-88b5-4329-8dd2-82d425e6f1b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/04 - Annuler l article au statut generé</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b492515c-4b72-44a6-a71b-dfdec01a14b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/05 - Envoyer l article au statut generé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afba9440-a1f7-41ac-9ed3-8385fa296ed3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c8e6b18-4741-4842-ab1b-efd14c98f755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc00e9c-b787-4785-a259-6d58b4e1b43e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f651364-cc43-4804-8438-871d3d6dc736</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfadaeec-004f-47b8-bc05-ebac698560b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/06 - Consulter le détail de transfert</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b64c8cd0-84c3-43d6-9a7e-473d049a2959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>597f7c77-3a6e-4d4e-a3ad-552a5f4c6426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b4a5063-13cc-4af6-b55c-8a3cc4fff109</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc5b9b5b-1fdd-437b-a3a2-90384037d370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f539fe35-0d00-4408-bfba-13c4d573d9c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c2a4bf-1ce8-442b-9c9f-76052bceefc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3791db50-8ce1-45ef-84ac-d3e833de71dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ed95588-a3c5-4623-a46f-48ff3cb843a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/07 - Annuler le transfert depuis la page de reception</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d3d5ed8-60a1-4829-83e6-4cacc1a667cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>071a6de2-95b3-4c0a-b117-66e0f41d89c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/05 - Envoyer l article au statut generé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afba9440-a1f7-41ac-9ed3-8385fa296ed3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c8e6b18-4741-4842-ab1b-efd14c98f755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc00e9c-b787-4785-a259-6d58b4e1b43e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f651364-cc43-4804-8438-871d3d6dc736</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e94e8cd-7004-48a5-bcd8-52e63e166e9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/08 - Filtrer les résultats TR-Sortie</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>673a4501-8bcd-4a60-93e9-ecac2e83bf6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55d9bdbb-f6d8-4abe-9dd1-22f5a77473c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/09 - Filtrer les résultats TR-Reception</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1115cd21-00bc-4cb9-b060-32c18bf371fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>541ddd68-b49f-4757-ab50-ea7580f5105a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smock Test POS/13 - Gestion de stock/Sortie et reception de transfert/10 - Receptionner le TR</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>606ce157-b101-4a18-973b-f2dfdcfe8af7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d015a3a-18fe-4c8f-a2ef-27424b770dc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b306568-ba42-4a2b-8b2b-94cca4bd4e3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cd93763-106d-473f-b376-942ddb319ac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c43936-722c-4dc6-854c-23f5f69b44d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39f2a4cf-c95e-42d2-928e-421ac0d95aa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24cc65b-e116-4bde-b194-ab08e20daea8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
